name: 'terraform-ci-ping'
description: 'Acknowledge ping test'
inputs:
  token:
    description: "github token"
    required: true
  test-name:
    description: "name of the github action status check that will be calling this action as a step"
    required: true
  sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Acknowledge ping"
      uses: cloudposse/github-action-terraform-ci/actions/status@main
      with:
        token: ${{ inputs.token }}
        test-name: ${{ inputs.test-name }}
        sha: ${{ inputs.sha }}
        status: "ping"
