name: 'terraform-ci'
description: 'Run chatops github actions'
inputs:
  token:
    description: "public repo access token"
    required: true
  reaction-token:
    description: "github token"
    reuired: true
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
    - name: "Handle common commands"
      uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
      with:
        token: ${{ inputs.token }}
        reaction-token: ${{ inputs.reaction-token }}
        reactions: false
        repository: cloudposse/actions
        commands: rebuild-readme, terraform-fmt
        permission: triage
        issue-type: pull-request
#    - name: "Run tests"
#      uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: test
#        permission: triage
#        issue-type: pull-request
#        reactions: false
