name: 'terraform-ci'
description: 'Run chatops github actions'
inputs:
  token:
    description: "public repo access token"
    required: true
  reaction-token:
    description: "github token"
    reuired: true
runs:
  using: "composite"
#  using: 'docker'
#  image: 'cloudposse/test-harness:latest'
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
    - name: "Test /test bats"
      if: ${{ github.event.comment.body == '/test bats'}}
      uses: docker://cloudposse/test-harness:latest
      env:
        MAKE_INCLUDES: Makefile
        TF_PLUGIN_CACHE_DIR: /tmp
      with:
        entrypoint: make
        args: "-C test/ clean init"
    - name: "Test /test bats"
      if: ${{ github.event.comment.body == '/test bats' and success() }}
      uses: docker://cloudposse/test-harness:latest
      env:
        MAKE_INCLUDES: Makefile
        TF_PLUGIN_CACHE_DIR: /tmp
      with:
        entrypoint: make
        args: "-C test/ module"
    - name: "Test /test bats"
      if: ${{ github.event.comment.body == '/test bats' and success() }}
      uses: docker://cloudposse/test-harness:latest
      env:
        MAKE_INCLUDES: Makefile
        TF_PLUGIN_CACHE_DIR: /tmp
      with:
        entrypoint: make
        args: "-C test/ examples/complete"
    - name: "Record successful '/test bats' result"
      if: ${{ github.event.comment.body == '/test bats' && success() }}
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue
          github.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "+1",
          });
    - name: "Record unsuccessful '/test bats' result"
      if: ${{ github.event.comment.body == '/test bats' && failure() }}
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue
          github.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "-1",
          });

#    - name: "Handle common commands"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: rebuild-readme, terraform-fmt
#        permission: triage
#        issue-type: pull-request
#    - name: "Run tests"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: test
#        permission: triage
#        issue-type: pull-request
#        reactions: false
