name: 'terraform-ci'
description: 'Run chatops github actions'
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Get metadata (SHA of pull request branch and exact test requested)"
      id: metadata
      uses: actions/github-script@v4
      with:
        script: |
          // extract the SHA of the commit at the head of the PR
          const prUrl = context.payload.issue.pull_request.url;
          const prDetails = await github.request(`GET ${prUrl}`);
          let headSha = prDetails.data.head.sha;
          core.setOutput("pr-sha", headSha);
          // extract the name of the test suite to be run
          const commentBody = context.payload.comment.body;
          const testRegex = /^\/test (\S+)\s*$/g;
          testMatches = commentBody.Match(testRegex);
          if (typeof testMatches[0] == "undefined") { // this indicates no /test command was found
            core.setOutput("test-name", "none")
          } else if (testMatches[1]) { // this should be the first capture group in a successful match
            core.setOutput("test-name", testMatches[1])
          }
      #core.setOutput("comment-body", commentBody);

    - name: "Handle bats command"
      if: steps.metadata.outputs.test-name == "bats" || steps.metadta.outputs.test-name == "all"
      uses: cloudposse/github-action-terraform-ci/actions/bats@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-bats"
        sha: ${{ steps.metadata.outputs.pr-sha }}

    - name: "Unrecognized /test command"
      if: steps.metadata.outputs.test-name != "bats" && steps.metadata.outputs.test-name != "all" && steps.metadata.outputs.test-name != "none"
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue
          github.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: "${{ github.event.comment.id }}",
            content: "-1",
          });


#    - name: "Handle common commands"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: rebuild-readme, terraform-fmt
#        permission: triage
#        issue-type: pull-request
#    - name: "Run tests"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: test
#        permission: triage
#        issue-type: pull-request
#        reactions: false
