name: 'terraform-ci'
description: "Run CI for Terraform (with support for chatops)"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Extract Necessary Metadata"
      uses: cloudposse/github-action-terraform-ci/actions/metadata@main

    - name: "Respond to chatops comment"
      if: github.event.comment
      uses: cloudposse/github-action-terraform-ci/actions/comment-response@main
      with:
        comment_id: ${{ github.event.comment.id }}
        tests_names: ${{ steps.metadata.outputs.tests-names }}

    - name: "Record pending status for all forthcoming checks"
      uses: cloudposse/github-action-terraform-ci/actions/all-statuses-pending@main
      with:
        token: ${{ inputs.token }}
        test-names: ${{ steps.metadata.outputs.tests-names }}
        sha: ${{ steps.metadata.outputs.pr-sha }}

    - name: "Run all requested tests"
      if: contains(steps.metadata.outputs.tests_names, 'unrecognized') != true && contains(steps.metadata.outputs.tests_names, 'none') != true
      uses: cloudposse/github-action-terraform-ci/actions/run-tests@main
      with:
        token: ${{ inputs.token }}
        tests-names: ${{ steps.metadata.outputs.tests-names }}
        sha: ${{ steps.metadata.outputs.pr-sha }}
        base-ref: ${{ steps.metadata.outputs.pr-base-ref }}
        labels: ${{ steps.metadata.outputs.pr-labels }}

    - name: "Record cancelled status for all pending and completed checks, if necessary"
      if: cancelled()
      uses: cloudposse/github-action-terraform-ci/actions/all-statuses-cancelled@main
      with:
        token: ${{ inputs.token }}
        test-names: ${{ steps.metadata.outputs.tests-names }}
        sha: ${{ steps.metadata.outputs.pr-sha }}

#    - name: "Handle common commands"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: rebuild-readme, terraform-fmt
#        permission: triage
#        issue-type: pull-request
#    - name: "Run tests"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: test
#        permission: triage
#        issue-type: pull-request
#        reactions: false
