name: 'terraform-ci'
description: "Run CI for Terraform (with support for chatops)"
inputs:
  token:
    description: "github token"
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  CLOUDFLARE_EMAIL:
    required: false
    default: ""
  CLOUDFLARE_API_KEY:
    required: false
    default: ""
  DD_API_KEY:
    required: false
    default: ""
  DD_APP_KEY:
    required: false
    default: ""
  OPSGENIE_API_KEY:
    required: false
    default: ""
  SPOTINST_ACCOUNT:
    required: false
    default: ""
  SPOTINST_TOKEN:
    required: false
    default: ""
  TFE_TOKEN:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Extract Necessary Metadata"
      id: metadata
      uses: cloudposse/github-action-terraform-ci/actions/metadata@main

    - name: "Respond to chatops comment"
      if: github.event.comment && contains(steps.metadata.outputs.valid-test-request, 'true')
      uses: cloudposse/github-action-terraform-ci/actions/comment-response@main
      with:
        comment_id: ${{ github.event.comment.id }}
        recognized_tests: ${{ steps.metadata.outputs.recognized-tests }}
        unrecognized_tests: ${{ steps.metadata.outputs.unrecognized-tests }}

    - name: "Record pending status for all forthcoming checks"
      uses: cloudposse/github-action-terraform-ci/actions/bulk-status-update@main
      with:
        token: ${{ inputs.token }}
        test-names: ${{ steps.metadata.outputs.recognized-tests }}
        sha: ${{ steps.metadata.outputs.pr-sha }}
        status: 'pending'

    - name: "Run all requested tests"
      uses: cloudposse/github-action-terraform-ci/actions/run-tests@main
      with:
        token: ${{ inputs.token }}
        tests-names: ${{ steps.metadata.outputs.recognized-tests }}
        pr-sha: ${{ steps.metadata.outputs.pr-sha }}
        base-ref: ${{ steps.metadata.outputs.pr-base-ref }}
        labels: ${{ steps.metadata.outputs.pr-labels }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_EMAIL: ${{ inputs.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_API_KEY: ${{ inputs.CLOUDFLARE_API_KEY }}
        DD_API_KEY: ${{ inputs.DD_API_KEY }}
        DD_APP_KEY: ${{ inputs.DD_APP_KEY }}
        OPSGENIE_API_KEY: ${{ inputs.OPSGENIE_API_KEY }}
        SPOTINST_ACCOUNT: ${{ inputs.SPOTINST_ACCOUNT }}
        SPOTINST_TOKEN: ${{ inputs.SPOTINST_TOKEN }}
        TFE_TOKEN: ${{ inputs.TFE_TOKEN }}

    - name: "Record cancelled status for all pending and completed checks, if necessary"
      if: cancelled()
      uses: cloudposse/github-action-terraform-ci/actions/bulk-status-update@main
      with:
        token: ${{ inputs.token }}
        test-names: ${{ steps.metadata.outputs.recognized-tests }}
        sha: ${{ steps.metadata.outputs.pr-sha }}
        status: 'error'

#    - name: "Handle common commands"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: rebuild-readme, terraform-fmt
#        permission: triage
#        issue-type: pull-request
#    - name: "Run tests"
#      uses: peter-evans/slash-command-dispatch@v2.3.0
#      #uses: cloudposse/actions/github/slash-command-dispatch@0.22.0
#      with:
#        token: ${{ inputs.token }}
#        reaction-token: ${{ inputs.reaction-token }}
#        repository: cloudposse/actions
#        commands: test
#        permission: triage
#        issue-type: pull-request
#        reactions: false
