name: "terraform-ci"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  terraform-ci:
    # only run on pull requests so long as they don't come from forks
    if: ( (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository) ) || (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: "Run common commands and tests, including when triggered via chatops"
        uses: cloudposse/github-action-terraform-ci@main
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
          SPOTINST_ACCOUNT: ${{ secrets.SPOTINST_ACCOUNT }}
          SPOTINST_TOKEN: ${{ secrets.SPOTINST_TOKEN }}
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
