name: 'ci-terraform-determine-terraform-version'
description: 'Determine the version of Terraform installe in the latest cloudposse/test-harness Docker image'
inputs:
  base-ref:
    description: "Name of the branch into which this PR wants to merge"
    required: true
  app_checkout_path:
    description: 'The path to checkout the application repository to during the workflow run'
    default: ./github-action-ci-terraform
    required: false
  labels:
    description: "Labels on this PR, including associated metadata"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout ci-terraform repo to load script locally on runner"
      uses: actions/checkout@v2
      with:
        repository: cloudposse/github-action-ci-terraform
        path: ${{ inputs.app_checkout_path }}

    - name: "Determine required Terraform version"
      uses: docker://cloudposse/test-harness:latest
      env:
        BASE_REF: ${{ inputs.base-ref }}
        LABELS: ${{ join(inputs.labels.*.name, '\n') }}
      with:
        entrypoint: "/github/workspace/${{ inputs.app_checkout_path }}/actions/utilities/determine-terraform-version/determine_terraform_version.sh"
