name: 'terraform-ci-readme'
description: 'Run readme tests'
inputs:
  token:
    description: "github token"
    required: true
  test-name:
    description: "name of the github action status check that will be calling this action as a step"
    required: true
  sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
  env:
    default: |
      MAKE_INCLUDES=Makefile
      BUILD_HARNESS_BRANCH=master
runs:
  using: "composite"
  steps:
    - name: "Update ENV"
      shell: bash
      run: |
        echo $INPUT_ENV > $GITHUB_ENV

    - name: "Record status"
      uses: cloudposse/github-action-terraform-ci/actions/status@main
      with:
        token: ${{ inputs.token }}
        test-name: ${{ inputs.test-name }}
        sha: ${{ inputs.sha }}
        comment_id: ${{ github.event.comment.id }}
        request_understood: true

    - name: "Initialize build-harness"
      uses: docker://cloudposse/test-harness:latest
      with:
        args: "init"

#    - name: "Test that README.md was generated from README.yaml"
#      uses: docker://cloudposse/test-harness:latest
#      with:
#        args: "readme/lint"

    - name: "Record status"
      if: always()
      uses: cloudposse/github-action-terraform-ci/actions/status@main
      with:
        token: ${{ inputs.token }}
        test-name: ${{ inputs.test-name }}
        sha: ${{ inputs.sha }}
        status: ${{ github.action_status }}
