name: "terraform-ci-command-terraform-fmt"
description: "Format terraform files"
inputs:
  token:
    description: 'Token that will be used to checkout the repo. The standard secrets.GITHUB_TOKEN token should do.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: cloudposse/github-action-auto-format@review-branch
      with:
        script-names: terraform_format
        workflow-token: ${{ inputs.token }}
        bot-name: cloudpossebot
