name: 'ci-terraform-handle-tests'
description: 'Run all requested tests'
inputs:
  token:
    description: "github token"
    required: true
  tests-names:
    description: "Names of all github action status checks that will be called"
    required: true
  pr-sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
  base-ref:
    desription: "The name of the base branch that's being merged into"
    required: true
  labels:
    description: "The labels attached to this PR"
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  CLOUDFLARE_EMAIL:
    required: false
    default: ""
  CLOUDFLARE_API_KEY:
    required: false
    default: ""
  DD_API_KEY:
    required: false
    default: ""
  DD_APP_KEY:
    required: false
    default: ""
  OPSGENIE_API_KEY:
    required: false
    default: ""
  SPOTINST_ACCOUNT:
    required: false
    default: ""
  SPOTINST_TOKEN:
    required: false
    default: ""
  TFE_TOKEN:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Handle bats command"
      if: (contains(inputs.tests-names, 'bats') || contains(inputs.tests-names, 'all')) && (success() || failure())
      uses: cloudposse/github-action-ci-terraform/actions/tests/bats@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-bats"
        sha: ${{ inputs.pr-sha }}

    - name: "Handle ping command"
      if: contains(inputs.tests-names, 'ping') || contains(inputs.tests-names, 'all') && (success() || failure())
      uses: cloudposse/github-action-ci-terraform/actions/tests/ping@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-ping"
        sha: ${{ inputs.pr-sha }}

    - name: "Handle readme command"
      if: contains(inputs.tests-names, 'readme') || contains(inputs.tests-names, 'all') && (success() || failure())
      uses: cloudposse/github-action-ci-terraform/actions/tests/readme@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-readme"
        sha: ${{ inputs.pr-sha }}

    - name: "Handle terratest command"
      if: contains(inputs.tests-names, 'terratest') || contains(inputs.tests-names, 'all') && (success() || failure())
      uses: cloudposse/github-action-ci-terraform/actions/tests/terratest@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-terratest"
        sha: ${{ inputs.pr-sha }}
        base-ref: ${{ inputs.base-ref }}
        labels: ${{ inputs.labels }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_EMAIL: ${{ inputs.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_API_KEY: ${{ inputs.CLOUDFLARE_API_KEY }}
        DD_API_KEY: ${{ inputs.DD_API_KEY }}
        DD_APP_KEY: ${{ inputs.DD_APP_KEY }}
        OPSGENIE_API_KEY: ${{ inputs.OPSGENIE_API_KEY }}
        SPOTINST_ACCOUNT: ${{ inputs.SPOTINST_ACCOUNT }}
        SPOTINST_TOKEN: ${{ inputs.SPOTINST_TOKEN }}
        TFE_TOKEN: ${{ inputs.TFE_TOKEN }}
