name: 'terraform-ci-runs'
description: 'Run tests'

on:
  workflow_call:
    inputs:
      tests:
        required: true
        type: string
      pr-sha:
        required: true
        type: string

jobs:
  ping:
    name: "Run ping test"
    runs-on: ubuntu-latest
    if: contains( inputs.tests, 'ping')
    steps:
      - uses: cloudposse/github-action-terraform-ci/actions/ping@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          test-name: "tests-ping"
          sha: ${{ inputs.pr-sha }}

  bats:
    name: "Run bats tests"
    runs-on: ubuntu-latest
    if: contains( inputs.tests, 'bats')
    steps:
      - uses: cloudposse/github-action-terraform-ci/actions/bats@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          test-name: "tests-bats"
          sha: ${{ inputs.pr-sha }}

  readme:
    name: "Run readme tests"
    runs-on: ubuntu-latest
    if: contains( inputs.tests, 'readme')
    steps:
      - uses: cloudposse/github-action-terraform-ci/actions/readme@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          test-name: "tests-readme"
          sha: ${{ inputs.pr-sha }}
