name: 'ci-terraform-bulk-status-update'
description: 'Update the statuses of all requested checks'
inputs:
  token:
    description: "github token"
    required: true
  sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
  test-names:
    description: "Names of the github action status checks to set to pending"
    required: true
  status:
    description: "Status to update checks to. Options include ['pending', 'error', failure', 'success']"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set status of bats test"
      if: contains(inputs.test-names, 'bats') || contains(inputs.test-names, 'all')
      uses: cloudposse/github-action-ci-terraform/actions/status@javascript-reorganization
      with:
        token: ${{ inputs.token }}
        test-name: 'tests-bats'
        sha: ${{ inputs.sha }}
        status: ${{ inputs.status }}

    - name: "Set status of ping test"
      if: contains(inputs.test-names, 'ping') || contains(inputs.test-names, 'all')
      uses: cloudposse/github-action-ci-terraform/actions/status@javascript-reorganization
      with:
        token: ${{ inputs.token }}
        test-name: 'tests-ping'
        sha: ${{ inputs.sha }}
        status: ${{ inputs.status }}

    - name: "Set status of readme test"
      if: contains(inputs.test-names, 'readme') || contains(inputs.test-names, 'all')
      uses: cloudposse/github-action-ci-terraform/actions/status@javascript-reorganization
      with:
        token: ${{ inputs.token }}
        test-name: 'tests-readme'
        sha: ${{ inputs.sha }}
        status: ${{ inputs.status }}

    - name: "Set status of terratest test"
      if: contains(inputs.test-names, 'terratest') || contains(inputs.test-names, 'all')
      uses: cloudposse/github-action-ci-terraform/actions/status@javascript-reorganization
      with:
        token: ${{ inputs.token }}
        test-name: 'tests-terratest'
        sha: ${{ inputs.sha }}
        status: ${{ inputs.status }}
