name: 'terraform-ci'
description: 'Run chatops github actions'
inputs:
  token:
    description: "github token"
    required: true
  test-name:
    description: "name of the github action status check that will be calling this action as a step"
    required: true
  sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
env:
  MAKE_INCLUDES: Makefile
  TF_PLUGIN_CACHE_DIR: /tmp
runs:
  using: "composite"
  steps:
    - name: "Acknowledge '/test bats'"
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue
          github.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "+1",
          });

    - name: "Record pending '/test bats' result"
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ inputs.token }}
        context: ${{ inputs.test-name }}
        description: 'Computing...'
        state: 'pending'
        sha: ${{ inputs.sha }}

    - name: "Initialize test-harness"
      uses: docker://cloudposse/test-harness:latest
      with:
        args: "-C test/ clean init"

    - name: "Test the module"
      uses: docker://cloudposse/test-harness:latest
      with:
        args: "-C test/ module"

    - name: "Test examples/complete"
      uses: docker://cloudposse/test-harness:latest
      with:
        args: "-C test/ examples/complete"

    - name: "Record status"
      uses: cloudposse/github-action-terraform-ci/actions/status@main
      with:
        token: ${{ inputs.token }}
        test-name: "tests-bats"
        sha: ${{ steps.pr-sha.outputs.pr-sha }}
        status: ${{ github.action_status }}
