name: 'terraform-ci-utilities-execute-terratest'
description: 'Execute Terratest functionality'
inputs:
  app_checkout_path:
    description: 'The path to checkout the application repository to during the workflow run'
    default: ./github-action-terraform-ci
    required: false
runs:
  using: "composite"
  steps:
    - name: "Checkout terraform-ci repo to load script locally on runner"
      uses: actions/checkout@v2
      with:
        repository: cloudposse/github-action-terraform-ci
        path: ${{ inputs.app_checkout_path }}

    - name: "Determine required Terraform version"
      uses: docker://cloudposse/test-harness:latest
      with:
        entrypoint: "/github/workspace/${{ inputs.app_checkout_path }}/actions/utilities/execute-terratest/terratest_functionality.sh"
