name: 'terraform-ci-run-commands'
description: 'Run all requested commands'
inputs:
  commands-names:
    description: "Names of all commands that will be called"
    required: true
  token:
    description: 'Token that will be used to checkout the repo. The standard secrets.GITHUB_TOKEN token should do.'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run rebuild-readme command"
      if: (contains(inputs.commands-names, 'rebuild-readme') || contains(inputs.commands-names, 'all')) && (success() || failure())
      uses: cloudposse/github-action-terraform-ci/actions/commands/rebuild-readme@review-branch
      with:
        token: ${{ inputs.token }}

    - name: "Run terraform command"
      if: (contains(inputs.commands-names, 'terraform-fmt') || contains(inputs.commands-names, 'all')) && (success() || failure())
      uses: cloudposse/github-action-terraform-ci/actions/commands/terraform-fmt@review-branch
      with:
        token: ${{ inputs.token }}
