name: 'ci-terraform-comment-response'
description: 'Respond to chatops comments to indicate the action being taken'
inputs:
  comment_id:
    description: "ID of comment which triggered this action"
    required: true
  recognized_tests:
    description: "Names of all tests to be run, or '' if if no valid tests were requested"
    required: true
  unrecognized_tests:
    description: "Names of all invalid tests requested, or '' if no invalid tests were requested"
    required: true
  recognized_runs:
    description: "Names of all runs to be executed, or '' if if no valid runs were requested"
    required: true
  unrecognized_runs:
    description: "Names of all invalid runs requested, or '' if no invalid runs were requested"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Respond to chatops comments"
      uses: actions/github-script@v4
      with:
        script: |
          const actionContext = require('${{ github.action_path }}/../../lib/actioncontext.js')(this, context, core, github, ${{ toJSON(github) }}, ${{ toJSON(inputs) }}, ${{ toJSON(steps) }})
          const commentResponder = require('${{ github.action_path }}/../../lib/comment-response.js').CommentResponder(actionContext)
          commentResponder.respond()
