name: 'ci-terraform-status'
description: 'Update the status for a given commit and respond to chatops comments with a thumb up or down'
inputs:
  token:
    description: "github token"
    required: true
  sha:
    description: "SHA hash of the commit whose status will be modified"
    required: true
  test-name:
    description: "name of the github action status check that will be calling this action as a step"
    required: true
  status:
    description: "Result of status check"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Acknowledge ping test"
      if: inputs.status == 'ping'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ inputs.token }}
        context: ${{ inputs.test-name }}
        description: 'PONG'
        state: 'success'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: "Record successful result"
      if: inputs.status == 'success'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ inputs.token }}
        context: ${{ inputs.test-name }}
        description: 'All tests passed'
        state: 'success'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: "Record canceled result"
      if: inputs.status == 'canceled' || inputs.status == 'error'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ inputs.token }}
        context: ${{ inputs.test-name }}
        description: 'Tests were cancelled by user'
        state: 'error'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: "Record unsuccessful result"
      if: inputs.status == 'failure'
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ inputs.token }}
        context: ${{ inputs.test-name }}
        description: 'One or more tests failed'
        state: 'failure'
        sha: ${{ inputs.sha }}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
