name: "ci-terraform-command-rebuild-readme"
description: "Rebuild readme"
inputs:
  token:
    description: 'Token that will be used to checkout the repo. The standard secrets.GITHUB_TOKEN token should do.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: cloudposse/github-action-auto-format@javascript-reorganization
      with:
        script-names: readme
        workflow-token: ${{ inputs.token }}
        bot-name: cloudpossebot
