name: "auto-release"
on:
  push:
    branches:
      - main
      - master
      - production

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-release@main
      with:
        prerelease: false
        publish: true
        token: ${{ secrets.GITHUB_TOKEN }}
